Activiti 3760 project release version libs
AlfrescoArchive/activiti-core-common pull request #108
Opened 2019-09-09 14:22 UTC by miguelruizdev

Solving https://issues.alfresco.com/jira/browse/ACTIVITI-3760

2019-09-09 16:47 UTC, ffazzini commented on activiti-spring-project/src/main/java/org/activiti/core/common/spring/project/ProjectModelService.java
> +    private String appName;
applicationName?

2019-09-09 16:48 UTC, ffazzini commented on activiti-spring-project/src/main/java/org/activiti/core/common/spring/project/ProjectModelService.java
> +    private ProjectManifest read (InputStream inputStream) throws IOException {
reformat file

2019-09-09 16:49 UTC, ffazzini commented on activiti-spring-project/src/main/java/org/activiti/core/common/spring/project/ProjectModelService.java
> +        Optional<Resource> resourceOptional = retrieveResource();
maybe a good spot for optional or else throw?

2019-09-09 16:52 UTC, ffazzini commented on activiti-spring-project/src/main/java/org/activiti/core/common/spring/project/autoconfigure/ProjectModelConfiguration.java
> +    public ProjectModelService projectModelService (@Value("${activiti.application.manifest.file.path=classpath:/}") String path,
can we just leave "${activiti.application.manifest.file.path}" ?

2019-09-09 16:53 UTC, ffazzini commented on activiti-spring-project/src/main/java/org/activiti/core/common/spring/project/autoconfigure/ProjectModelConfiguration.java
> +    public String projectReleaseVersion(ProjectModelService projectModelService) throws IOException {
can we expose as a bean the whole ProjectManifest object in case we need to reuse other properties in the future?

2019-09-10 15:00 UTC, erdemedeiros requested changes
One question and one small detail.

2019-09-10 15:00 UTC, erdemedeiros commented on activiti-spring-project/pom.xml
> +      <artifactId>activiti-connector-model</artifactId>
Why is it depending on connector-model?

2019-09-10 15:00 UTC, erdemedeiros commented on activiti-spring-project/pom.xml
> +      <artifactId>activiti-project-model</artifactId>
Please, move this dependency up (before dependencies in `test` scope).

2019-09-10 15:02 UTC, miguelruizdev commented on activiti-spring-project/pom.xml
> +      <artifactId>activiti-connector-model</artifactId>
Mistake :)

2019-09-11 09:25 UTC, erdemedeiros approved these changes

2019-09-11 09:42 UTC, merged